//
// Generated file, do not edit! Created by nedtool 5.6 from veins_inet/vfognetsim/edgeMessages/MIPSAdvertisementByEdge.msg.
//

#ifndef __MIPSADVERTISEMENTBYEDGE_M_H
#define __MIPSADVERTISEMENTBYEDGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class MIPSAdvertisementByEdge;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>veins_inet/vfognetsim/edgeMessages/MIPSAdvertisementByEdge.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // Example message definition
 * //
 * class MIPSAdvertisementByEdge extends inet::FieldsChunk
 * {
 *     int rm_MIPS;
 *     int edgeID;
 * }
 * </pre>
 */
class MIPSAdvertisementByEdge : public ::inet::FieldsChunk
{
  protected:
    int rm_MIPS = 0;
    int edgeID = 0;

  private:
    void copy(const MIPSAdvertisementByEdge& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MIPSAdvertisementByEdge&);

  public:
    MIPSAdvertisementByEdge();
    MIPSAdvertisementByEdge(const MIPSAdvertisementByEdge& other);
    virtual ~MIPSAdvertisementByEdge();
    MIPSAdvertisementByEdge& operator=(const MIPSAdvertisementByEdge& other);
    virtual MIPSAdvertisementByEdge *dup() const override {return new MIPSAdvertisementByEdge(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRm_MIPS() const;
    virtual void setRm_MIPS(int rm_MIPS);
    virtual int getEdgeID() const;
    virtual void setEdgeID(int edgeID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MIPSAdvertisementByEdge& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MIPSAdvertisementByEdge& obj) {obj.parsimUnpack(b);}

#endif // ifndef __MIPSADVERTISEMENTBYEDGE_M_H

