//
// Generated file, do not edit! Created by nedtool 5.6 from veins_inet/vfognetsim/mecoMessages/CollectRequests.msg.
//

#ifndef __COLLECTREQUESTS_M_H
#define __COLLECTREQUESTS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class CollectRequests;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>veins_inet/vfognetsim/mecoMessages/CollectRequests.msg:20</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class CollectRequests extends inet::FieldsChunk
 * {
 *     int mecoID;
 *     int rsuID;
 *     int numReqs;
 *     int rq_MIPS;
 *     int taskSize;
 *     float delayTol;
 *     int vehicleID;
 *     int index;
 *     float bw;
 *     float cap;
 *     double Tsys;
 * }
 * </pre>
 */
class CollectRequests : public ::inet::FieldsChunk
{
  protected:
    int mecoID = 0;
    int rsuID = 0;
    int numReqs = 0;
    int rq_MIPS = 0;
    int taskSize = 0;
    float delayTol = 0;
    int vehicleID = 0;
    int index = 0;
    float bw = 0;
    float cap = 0;
    double Tsys = 0;

  private:
    void copy(const CollectRequests& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CollectRequests&);

  public:
    CollectRequests();
    CollectRequests(const CollectRequests& other);
    virtual ~CollectRequests();
    CollectRequests& operator=(const CollectRequests& other);
    virtual CollectRequests *dup() const override {return new CollectRequests(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMecoID() const;
    virtual void setMecoID(int mecoID);
    virtual int getRsuID() const;
    virtual void setRsuID(int rsuID);
    virtual int getNumReqs() const;
    virtual void setNumReqs(int numReqs);
    virtual int getRq_MIPS() const;
    virtual void setRq_MIPS(int rq_MIPS);
    virtual int getTaskSize() const;
    virtual void setTaskSize(int taskSize);
    virtual float getDelayTol() const;
    virtual void setDelayTol(float delayTol);
    virtual int getVehicleID() const;
    virtual void setVehicleID(int vehicleID);
    virtual int getIndex() const;
    virtual void setIndex(int index);
    virtual float getBw() const;
    virtual void setBw(float bw);
    virtual float getCap() const;
    virtual void setCap(float cap);
    virtual double getTsys() const;
    virtual void setTsys(double Tsys);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CollectRequests& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CollectRequests& obj) {obj.parsimUnpack(b);}

#endif // ifndef __COLLECTREQUESTS_M_H

