//
// Generated file, do not edit! Created by nedtool 5.6 from veins_inet/vfognetsim/mecoMessages/MIPSAdvertisementByMeco.msg.
//

#ifndef __MIPSADVERTISEMENTBYMECO_M_H
#define __MIPSADVERTISEMENTBYMECO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class MIPSAdvertisementByMeco;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>veins_inet/vfognetsim/mecoMessages/MIPSAdvertisementByMeco.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // Example message definition
 * //
 * class MIPSAdvertisementByMeco extends inet::FieldsChunk
 * {
 *     int rm_MIPS;
 *     int mecoID;
 * }
 * </pre>
 */
class MIPSAdvertisementByMeco : public ::inet::FieldsChunk
{
  protected:
    int rm_MIPS = 0;
    int mecoID = 0;

  private:
    void copy(const MIPSAdvertisementByMeco& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MIPSAdvertisementByMeco&);

  public:
    MIPSAdvertisementByMeco();
    MIPSAdvertisementByMeco(const MIPSAdvertisementByMeco& other);
    virtual ~MIPSAdvertisementByMeco();
    MIPSAdvertisementByMeco& operator=(const MIPSAdvertisementByMeco& other);
    virtual MIPSAdvertisementByMeco *dup() const override {return new MIPSAdvertisementByMeco(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRm_MIPS() const;
    virtual void setRm_MIPS(int rm_MIPS);
    virtual int getMecoID() const;
    virtual void setMecoID(int mecoID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MIPSAdvertisementByMeco& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MIPSAdvertisementByMeco& obj) {obj.parsimUnpack(b);}

#endif // ifndef __MIPSADVERTISEMENTBYMECO_M_H

