//
// Generated file, do not edit! Created by nedtool 5.6 from veins_inet/vfognetsim/vehicleMessages/TaskCompletionAckByVehicle.msg.
//

#ifndef __TASKCOMPLETIONACKBYVEHICLE_M_H
#define __TASKCOMPLETIONACKBYVEHICLE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class TaskCompletionAckByVehicle;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>veins_inet/vfognetsim/vehicleMessages/TaskCompletionAckByVehicle.msg:26</tt> by nedtool.
 * <pre>
 * //
 * // Example message definition
 * //
 * class TaskCompletionAckByVehicle extends inet::FieldsChunk
 * {
 *     int vehicleID;
 *     int taskID;
 *     int rsuID;
 * }
 * </pre>
 */
class TaskCompletionAckByVehicle : public ::inet::FieldsChunk
{
  protected:
    int vehicleID = 0;
    int taskID = 0;
    int rsuID = 0;

  private:
    void copy(const TaskCompletionAckByVehicle& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TaskCompletionAckByVehicle&);

  public:
    TaskCompletionAckByVehicle();
    TaskCompletionAckByVehicle(const TaskCompletionAckByVehicle& other);
    virtual ~TaskCompletionAckByVehicle();
    TaskCompletionAckByVehicle& operator=(const TaskCompletionAckByVehicle& other);
    virtual TaskCompletionAckByVehicle *dup() const override {return new TaskCompletionAckByVehicle(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getVehicleID() const;
    virtual void setVehicleID(int vehicleID);
    virtual int getTaskID() const;
    virtual void setTaskID(int taskID);
    virtual int getRsuID() const;
    virtual void setRsuID(int rsuID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskCompletionAckByVehicle& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskCompletionAckByVehicle& obj) {obj.parsimUnpack(b);}

#endif // ifndef __TASKCOMPLETIONACKBYVEHICLE_M_H

